//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.Wizard.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.Wizard.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the age of the person.
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dynamic page.
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageView_AddDynamicPage {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageView_AddDynamicPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageView_Age {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageView_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add a new page to see the dynamic navigation pane behavior?.
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageViewModel_AddPageQuestion {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageViewModel_AddPageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add page?.
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageViewModel_AddPageTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageViewModel_AddPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.Wizard example.
        /// </summary>
        internal static string Orc_Wizard_Example_Common_AppTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Common_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP HANDLER.
        /// </summary>
        internal static string Orc_Wizard_Example_Common_HelpHandler {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Common_HelpHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string Orc_Wizard_Example_Common_SelectAll {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Common_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the components.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components selection with long title.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel via code.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_CancelViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_CancelViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the components you want to use:.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move back via code.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_MoveBackViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_MoveBackViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move forward via code.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_MoveForwardViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_MoveForwardViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move next or finish via code.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_MoveNextOrFinishViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_MoveNextOrFinishViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least 1 component.
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageViewModel_SelectAtLeast1Component {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageViewModel_SelectAtLeast1Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the gadgets.
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets.
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets.
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the gadgets you want to use:.
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very long page 1.
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long 1.
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dictum quam sed suscipit aliquet. Nam malesuada et eros id molestie. Phasellus lacinia eleifend nisi, vitae feugiat turpis laoreet in. Maecenas condimentum commodo metus nec tempor. Suspendisse potenti. Etiam interdum ante vitae est elementum iaculis. Mauris tempor orci ut dolor laoreet malesuada. Morbi tortor sapien, congue nec mauris ac, posuere elementum tortor. Aliquam interdum elementum risus eu egestas. Donec neque ipsum, finibus eget  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph1 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ut egestas lorem nec nisl accumsan fringilla. Maecenas gravida, nisl quis placerat blandit, odio ligula elementum neque, nec accumsan turpis mauris at orci. Vestibulum lorem ipsum, scelerisque eu sodales sit amet, sollicitudin vel dui. In hendrerit nulla a augue vulputate rutrum. Suspendisse facilisis justo id eros imperdiet facilisis. Nullam risus erat, ultricies non vehicula eu, congue et nulla. Pellentesque non laoreet mauris, ut mattis magna. Pellentesque porta efficitur risus, et posuere nisi mollis et [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph2 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morbi porta lorem sit amet magna varius iaculis. Donec condimentum tortor eu dignissim lobortis. Duis ac sagittis ante, id interdum eros. Suspendisse ultricies felis urna, ac tincidunt sem dapibus sed. In hendrerit mattis urna, non convallis lectus viverra vitae. Vestibulum sit amet ex leo. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac nisi aliquet, congue tellus id, aliquet nibh. Cras vehicula est et urna condimentum pharetra. Integer ex lacus, aliquam id dui lacinia, t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph3 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspendisse potenti. Suspendisse justo lectus, porta in pellentesque et, scelerisque in libero. Nulla posuere felis ut lacus dapibus, ac aliquet tortor tempor. Maecenas feugiat neque eget risus accumsan pharetra. Phasellus sed dolor lacus. Curabitur bibendum lobortis leo eleifend posuere. Phasellus tempus, ante non euismod tincidunt, leo lectus sollicitudin lectus, sed tristique mauris nisl accumsan ligula. Morbi odio velit, vulputate ut leo id, tempus finibus purus. Curabitur vestibulum urna vitae tincidun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph4 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sed fringilla, mi nec blandit ultricies, tortor nunc consequat sem, nec semper arcu justo vel nisi. Praesent scelerisque mauris eget mauris bibendum, at ultricies nunc dictum. Aliquam faucibus massa vitae sapien sollicitudin, nec dapibus tellus condimentum. Duis interdum elit et velit sollicitudin dictum. Suspendisse elementum mi quis sem molestie, a semper magna ultrices. Sed rutrum magna non metus sodales, eget mattis dui hendrerit. Quisque et nisl vehicula, varius erat facilisis, ullamcorper mauris. Maur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph5 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very long page 2.
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long 2.
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dictum quam sed suscipit aliquet. Nam malesuada et eros id molestie. Phasellus lacinia eleifend nisi, vitae feugiat turpis laoreet in. Maecenas condimentum commodo metus nec tempor. Suspendisse potenti. Etiam interdum ante vitae est elementum iaculis. Mauris tempor orci ut dolor laoreet malesuada. Morbi tortor sapien, congue nec mauris ac, posuere elementum tortor. Aliquam interdum elementum risus eu egestas. Donec neque ipsum, finibus eget  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph1 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ut egestas lorem nec nisl accumsan fringilla. Maecenas gravida, nisl quis placerat blandit, odio ligula elementum neque, nec accumsan turpis mauris at orci. Vestibulum lorem ipsum, scelerisque eu sodales sit amet, sollicitudin vel dui. In hendrerit nulla a augue vulputate rutrum. Suspendisse facilisis justo id eros imperdiet facilisis. Nullam risus erat, ultricies non vehicula eu, congue et nulla. Pellentesque non laoreet mauris, ut mattis magna. Pellentesque porta efficitur risus, et posuere nisi mollis et [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph2 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morbi porta lorem sit amet magna varius iaculis. Donec condimentum tortor eu dignissim lobortis. Duis ac sagittis ante, id interdum eros. Suspendisse ultricies felis urna, ac tincidunt sem dapibus sed. In hendrerit mattis urna, non convallis lectus viverra vitae. Vestibulum sit amet ex leo. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac nisi aliquet, congue tellus id, aliquet nibh. Cras vehicula est et urna condimentum pharetra. Integer ex lacus, aliquam id dui lacinia, t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph3 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspendisse potenti. Suspendisse justo lectus, porta in pellentesque et, scelerisque in libero. Nulla posuere felis ut lacus dapibus, ac aliquet tortor tempor. Maecenas feugiat neque eget risus accumsan pharetra. Phasellus sed dolor lacus. Curabitur bibendum lobortis leo eleifend posuere. Phasellus tempus, ante non euismod tincidunt, leo lectus sollicitudin lectus, sed tristique mauris nisl accumsan ligula. Morbi odio velit, vulputate ut leo id, tempus finibus purus. Curabitur vestibulum urna vitae tincidun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph4 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow quick navigation.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AllowQuickNavigation {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AllowQuickNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow quick navigation to visited pages.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AllowQuickNavigationToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AllowQuickNavigationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto size side navigation pane.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AutoSizeSideNavigationPane {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AutoSizeSideNavigationPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto sizing adjusts the spacing between the ellipses in navigation pane so they fit without scrolling. The spacing is calculated from the Wizard window minimum size (MinSize)..
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AutoSizeSideNavigationPaneToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AutoSizeSideNavigationPaneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache views (do not recreate on each page navigation).
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_CacheViews {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_CacheViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example will show you how to use the wizard elements in Orc.Wizard. The code is fairly easy to understand. Even though this demo isn&apos;t very meaningful it illustrates the real power of the wizard in combination with Catel:
        ///
        ///- State management (remember values when navigating between views)
        ///- Views can be used inside and outside of the wizard
        ///- Validation per view model or model
        ///- Easy to code, seriously, check it out for yourself!.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle navigation states.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_HandleNavigationStates {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_HandleNavigationStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all pages as visited before showing wizard.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_MarkAllPagesAsVisited {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_MarkAllPagesAsVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to other screen (if possible).
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_MoveToOtherScreen {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_MoveToOtherScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests the auto move logic and the page initialization logic..
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_MoveToOtherScreenToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_MoveToOtherScreenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full screen wizard....
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowFullScreenWizard {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowFullScreenWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help button.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowHelpButton {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowHelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the help button in the wizard.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowHelpButtonToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowHelpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in taskbar.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowInTaskbar {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show an icon in the taskbar for the wizard.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowInTaskbarToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowInTaskbarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show summary page.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowSummaryPage {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowSummaryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the summary page at the end of the wizard..
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowSummaryPageToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowSummaryPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show wizard....
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowWizard {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show wizard with side navigation....
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowWizardWithSideNavigation {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowWizardWithSideNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use fast forward navigation controller.
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_UseFastForwardNavigationController {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_UseFastForwardNavigationController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fast forward navigation controller allows to skip pages and go directly to the summary page. Or when there is no summary page, immediately resume from the wizard..
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_UseFastForwardNavigationControllerToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_UseFastForwardNavigationControllerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the details of the person.
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard page shows you how to map textbox elements to a model and validate them. Notice that you cannot move to the next page while the fields are not yet valid. When navigating forward and back, you will see the values are automatically restored.
        ///
        ///The cool thing is that the view model for this page only has 28 (!) lines of code. This means your pages stay small and are easily maintainable..
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageView_FirstName {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageView_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageView_LastName {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageView_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageViewModel_FirstNameRequired {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageViewModel_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageViewModel_LastNameRequired {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageViewModel_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the skills.
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your skills:.
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least 1 skill.
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPageViewModel_SelectAtLeast1Skill {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPageViewModel_SelectAtLeast1Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on it....
        /// </summary>
        internal static string Orc_Wizard_Example_SystemInfoView_WorkingOnIt {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SystemInfoView_WorkingOnIt", resourceCulture);
            }
        }
    }
}
