version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src"
    update_schedule: "daily"
    automerged_updates:
      - match:
        dependency_type: "production"
        update_type: "security:patch"
      - match:
        dependency_name: "Catel.*"
        update_type: "semver:minor"
      - match:
        dependency_name: "Orc.*"
        update_type: "semver:minor"
      - match:
        dependency_name: "Orchestra.*"
        update_type: "semver:minor"